name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Get queen-batch version
        id: queenbatch
        run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=queenbatch.version -q -DforceStdout)"

      - name: Clone queen-batch
        run: git clone https://github.com/InseeFr/Queen-Batch.git --depth 1 --branch ${{steps.queenbatch.outputs.prop}}

      - name: Install queen-batch
        run:  |
              cd Queen-Batch                                         
              mvn clean install -DskipTests --batch-mode --no-transfer-progress

      - name: Build and test with coverage
        timeout-minutes: 15
        run: mvn clean verify --batch-mode --no-transfer-progress

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/jacoco.xml