name: Build and Analyze

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - "*"

jobs:
  build-and-analyze:
    name: Build & Analyze with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Get queen-batch version
        id: queenbatch
        run: |
          echo "queenbatch_version=$(mvn help:evaluate -Dexpression=queenbatch.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Clone and install Queen-Batch
        run: |
            git clone https://github.com/InseeFr/Queen-Batch.git --depth 1 --branch ${{ steps.queenbatch.outputs.queenbatch_version }}
            cd Queen-Batch
            mvn clean install -DskipTests --batch-mode --no-transfer-progress

      - name: Build and test with coverage
        timeout-minutes: 15
        run: mvn clean verify sonar:sonar --batch-mode --no-transfer-progress \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.host.url=https://sonarcloud.io