name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get queen-batch version
        id: queenbatch
        run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=queenbatch.version -q -DforceStdout)"
      - name: Download queenbatch
        run: curl -L https://github.com/InseeFr/Queen-Batch/releases/download/${{steps.queenbatch.outputs.prop}}/queen-batch.jar -o queen-batch.jar  
      - name: Install queen-batch
        run: mvn install:install-file -Dfile=queen-batch.jar -DgroupId=fr.insee.queen -DartifactId=queen-batch -Dversion=${{steps.queenbatch.outputs.prop}} -Dpackaging=jar
      - name: Download lunatic-model
        run: curl -L https://github.com/InseeFr/Lunatic-Model/releases/download/2.2.3-rc/lunatic-model.jar -o lunatic-model.jar  
      - name: Install lunatic-model
        run: mvn install:install-file -Dfile=lunatic-model.jar -DgroupId=fr.insee.lunatic -DartifactId=lunatic-model -Dversion=2.2.3 -Dpackaging=jar
      - name: Build with Maven
        run: mvn clean install
