name: Release Candidate

on:
  push:
    branches:
      - 'develop'
    tags:
      - '*'

jobs:
    build-release:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: 21
            distribution: 'temurin'
        - name: Get queen-batch version
          id: queenbatch
          run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=queenbatch.version -q -DforceStdout)"

        - name: Clone queen-batch
          run: git clone https://github.com/InseeFr/Queen-Batch.git --depth 1 --branch ${{steps.queenbatch.outputs.prop}}

        - name: Install queen-batch
          run:  |
                cd Queen-Batch                                         
                mvn clean install -DskipTests --batch-mode --no-transfer-progress
        - name: Build with Maven
          timeout-minutes: 15
          run: mvn clean install --batch-mode --no-transfer-progress
        - name: Get current version
          id: version
          run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
        - run: echo ${{steps.version.outputs.prop}}
        - name: Create Release
          id: create_release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{steps.version.outputs.prop}}-rc
            release_name: Release Candidate ${{steps.version.outputs.prop}}
            draft: false
            prerelease: false    